on: [workflow_dispatch]
name: Linux_Container_frontend

permissions:
      id-token: write
      contents: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: szupee.azurecr.io
            username: ${{ secrets.AZURE_CLIENT_ID }}
            password: ${{ secrets.AZURE_CLIENT_SECRET }}
        - run: |
            docker build -f Dockerfile . -t ${{ secrets.AZURE_ACR }}/mathapp:latest
            docker push ${{ secrets.AZURE_ACR }}/mathapp:latest